name: publish-to-dockerhub
'on':
  push:
    branches:
      - main
jobs:
  api-platform-php:
    runs-on: ubuntu-latest
    environment: dockerhub
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: '${{ secrets.DOCKERHUB_USERNAME }}'
          password: '${{ secrets.DOCKERHUB_TOKEN }}'
      - name: Build and push api-platform-php
        id: api_platform_php
        uses: docker/build-push-action@v2
        with:
          target: api_platform_php
          push: true
          tags: 'hottomali/api-platform-php:latest'
          outputs: type=docker/dest=/tmp/api-platform-php.tar
      -
        name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: api_platform_php_image
          path: /tmp/myimage.tar
  api-platform-php-xdebug:
    runs-on: ubuntu-latest
    environment: dockerhub
    needs: api-platform-php
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: api_platform_php_image
          path: /tmp
      - name: Load image
        run: |
          docker load --input /tmp/myimage.tar
          docker image ls -a
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: '${{ secrets.DOCKERHUB_USERNAME }}'
          password: '${{ secrets.DOCKERHUB_TOKEN }}'
      - name: Build and push api-platform-php-xdebug
        id: api_platform_php_xdebug
        uses: docker/build-push-action@v2
        with:
          target: api_platform_php_xdebug
          push: true
          tags: 'hottomali/api-platform-php:latest'
