name: publish-to-dockerhub
'on':
  push:
    branches:
      - main
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: '${{ secrets.DOCKERHUB_USERNAME }}'
          password: '${{ secrets.DOCKERHUB_TOKEN }}'
      - name: Build and push api-platform-php
        id: api_platform_php
        uses: docker/build-push-action@v2
        with:
          context: .
          target: api_platform_php
          push: true
          tags: 'hottomali/api-platform-php:latest'
