name: publish-to-dockerhub
'on':
  push:
    branches:
      - main
jobs:
  api-platform-php:
    runs-on: ubuntu-latest
    environment: dockerhub
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: '${{ secrets.DOCKERHUB_USERNAME }}'
          password: '${{ secrets.DOCKERHUB_TOKEN }}'
      - name: Build and push api-platform-php
        id: api_platform_php
        uses: docker/build-push-action@v2
        with:
          target: api_platform_php
          push: true
          tags: 'hottomali/api-platform-php:latest'
      - name: Build and push api-platform-php-xdebug
        id: api_platform_php_xdebug
        uses: docker/build-push-action@v2
        with:
          target: api_platform_php_xdebug
          push: true
          tags: 'hottomali/api-platform-php:xdebug-latest'
      - name: Build and push api-platform-php-blackfire
        id: api_platform_php_blackfire
        uses: docker/build-push-action@v2
        with:
          target: api_platform_php_xdebug
          push: true
          tags: 'hottomali/api-platform-php:blackfire-latest'
      - name: Build and push api-platform-php-pcov
        id: api_platform_php_pcov
        uses: docker/build-push-action@v2
        with:
          target: api_platform_php_pcov
          push: true
          tags: 'hottomali/api-platform-php:pcov-latest'
